version: '3.8'

services:
  document-api:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "5172:80"  # Map host port 5000 to container port 80
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - MongoDb__ConnectionString=mongodb://mongo:27017
      - MongoDb__DatabaseName=DocumentManagementDb
      - Minio__Endpoint=minio:9000
      - Minio__AccessKey=minioadmin
      - Minio__SecretKey=minioadmin
    depends_on:
      - mongo
      - minio

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"  # Expose MongoDB on port 27017
    volumes:
      - mongo_data:/data/db  # Persistent storage for MongoDB

  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"  # MinIO API
      - "9001:9001"  # MinIO Console
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data
    volumes:
      - minio_data:/data  # Persistent storage for MinIO

volumes:
  mongo_data:
  minio_data: